name: Deployment workflow

on:
  push:
    branches:
      - master

jobs:
  check_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check for changes
        id: changes
        run: |
          CHANGED_FILES=$(git diff HEAD^ --name-only)
          echo ::set-output name=changes::$CHANGED_FILES
  prisma_migrate:
    needs: check_changes
    runs-on: ubuntu-latest
    if: contains(github.event.changes, 'prisma/schema.prisma')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Prisma
        run: npm install prisma -D
      - name: Deploy migrations
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
        run: npx prisma migrate deploy
